server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  redis:
    host: 49.232.83.17
    port: 6379
    database: 0
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true

logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: #xxxxxxx
    key-secret: # xxxxxxxx
    sign-name: 阿里云短信测试  # 目前是测试的name，模板通过了可以使用自己的name
    login-template-code: SMS_154950909  # 目前是测试的code，模板通过了可以使用自己的code
    register-template-code: SMS_239311301  # 模板申请未通过
    reset-template-code: SMS_239316348  # 模板申请未通过
